=begin
#BombBomb

#We make it easy to build relationships using simple videos.

OpenAPI spec version: 2.0.21432

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'spec_helper'
require 'json'

# Unit tests for BombBomb::CurriculumApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CurriculumApi' do
  before do
    # run before each test
    @instance = BombBomb::CurriculumApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CurriculumApi' do
    it 'should create an instact of CurriculumApi' do
      expect(@instance).to be_instance_of(BombBomb::CurriculumApi)
    end
  end

  # unit tests for get_curricula
  # Get Curricula
  # Get Curricula, optionally with progress included.
  # @param [Hash] opts the optional parameters
  # @option opts [BOOLEAN] :include_progress Whether to return progress with the curriculum.
  # @return [Array<Curriculum>]
  describe 'get_curricula test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_user_curriculum_with_progress
  # Get Detailed For User
  # Get all curricula for user including progress for each curriculum.
  # @param [Hash] opts the optional parameters
  # @return [Array<CurriculumWithProgress>]
  describe 'get_user_curriculum_with_progress test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
