=begin
#BombBomb

#We make it easy to build relationships using simple videos.

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'spec_helper'
require 'json'

# Unit tests for BombBomb::FormsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'FormsApi' do
  before do
    # run before each test
    @instance = BombBomb::FormsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FormsApi' do
    it 'should create an instact of FormsApi' do
      expect(@instance).to be_instance_of(BombBomb::FormsApi)
    end
  end

  # unit tests for get_form_tracking_as_csv
  # Get csv
  # Get form tracking as csv
  # @param id Id of the form
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'get_form_tracking_as_csv test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
