=begin
#BombBomb

#We make it easy to build relationships using simple videos.

OpenAPI spec version: 2.0.24005

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'spec_helper'
require 'json'

# Unit tests for BombBomb::ListsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ListsApi' do
  before do
    # run before each test
    @instance = BombBomb::ListsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ListsApi' do
    it 'should create an instact of ListsApi' do
      expect(@instance).to be_instance_of(BombBomb::ListsApi)
    end
  end

  # unit tests for clear_list
  # Clear Contacts from List
  # Clears all contacts from a list.
  # @param list_id The list to be cleared.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'clear_list test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for copy_list_contacts
  # Copy All Contacts from a List
  # Copy all contacts from a list.
  # @param from_list_id The list to be cleared.
  # @param list_id The list to be cleared.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'copy_list_contacts test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for suppress_all_in_list
  # Suppress All Contacts from List
  # Suppresses all contacts in a list.
  # @param list_id The list to be cleared.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'suppress_all_in_list test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
