=begin
#BombBomb

#We make it easy to build relationships using simple videos.

OpenAPI spec version: 2.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'spec_helper'
require 'json'

# Unit tests for BombBomb::TeamsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'TeamsApi' do
  before do
    # run before each test
    @instance = BombBomb::TeamsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TeamsApi' do
    it 'should create an instact of TeamsApi' do
      expect(@instance).to be_instance_of(BombBomb::TeamsApi)
    end
  end

  # unit tests for cancel_jericho_send
  # Cancel a Jericho Send
  # Cancels a scheduled Jericho send from being sent.
  # @param jericho_id ID of the Jericho Job to cancel
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'cancel_jericho_send test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_client_group_assets
  # Lists team assets
  # Returns a collection of assets
  # @param asset_type The type of assets.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :team_id The team containing the assets.
  # @option opts [String] :auto_tag_name The auto tag name containing the assets.
  # @option opts [String] :page_size The number of items to retrieve in a single db query.
  # @option opts [String] :page Zero-based index of the page of data to retrieve from the db.
  # @option opts [String] :search Search words.
  # @return [InlineResponse200]
  describe 'get_client_group_assets test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_jericho_sends
  # List Jericho Sends
  # Lists Jericho sends, both pending and sent.
  # @param team_id The team whose Jericho sends you wish to see.
  # @param [Hash] opts the optional parameters
  # @return [Array<JerichoConfiguration>]
  describe 'get_jericho_sends test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_jericho_stats
  # Gets Jericho performance statistics
  # Returns an aggregate view of the performance of a Jericho send
  # @param jericho_id ID of the Jericho job
  # @param team_id ID of team through which Jericho was sent
  # @param [Hash] opts the optional parameters
  # @return [JerichoPerformance]
  describe 'get_jericho_stats test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for queue_jericho_send
  # Creates a Jericho send.
  # Sends email content on behalf of members of a client group. There are two forms this send can take:         Static Email, and Video Prompt. Static emails require only an emailId.         Video Prompts build emails dynamically and require most of the other fields.         You must be an administrator of a Team Account to use this method.
  # @param config JSON representing a Jericho configuration
  # @param team_id The ID of the team.
  # @param [Hash] opts the optional parameters
  # @return [JerichoConfiguration]
  describe 'queue_jericho_send test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
