=begin
#BombBomb

#We make it easy to build relationships using simple videos.

OpenAPI spec version: 2.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'spec_helper'
require 'json'

# Unit tests for BombBomb::WebhooksApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'WebhooksApi' do
  before do
    # run before each test
    @instance = BombBomb::WebhooksApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of WebhooksApi' do
    it 'should create an instact of WebhooksApi' do
      expect(@instance).to be_instance_of(BombBomb::WebhooksApi)
    end
  end

  # unit tests for add_web_hook
  # Add Webhook
  # Idempotently adds a Webhook url
  # @param hook_url The Url of your listener
  # @param [Hash] opts the optional parameters
  # @return [BBWebHook]
  describe 'add_web_hook test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_web_hook
  # Deletes Webhook
  # Deletes a Webhook
  # @param hook_id The id of the webhook to delete
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'delete_web_hook test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_web_hooks
  # Lists Webhooks
  # Lists all registered Webhooks
  # @param [Hash] opts the optional parameters
  # @return [Array<BBWebHook>]
  describe 'get_web_hooks test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for send_webhook_example
  # Sends test Webhook
  # Triggers a test webhook to be sent to your endpoints.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'send_webhook_example test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
